# Generated by Django 5.2 on 2025-05-04 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('etat', models.CharField(max_length=50)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mecanicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparations', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparations', to='vehicules.vehicule')),
            ],
        ),
    ]
