# Generated by Django 5.2 on 2025-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparation',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
