# Generated by Django 5.2.1 on 2025-05-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecaniciens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanicien',
            name='specialite',
            field=models.CharField(max_length=30),
        ),
    ]
